name: publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 15.x
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install (with cache)
        uses: bahmutov/npm-install@v1

      - name: Build
        run: npm run build

      - name: Publish
        run: yarn lerna publish from-package --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
